_extends: .github:.github/release-drafts/increasing-patch-version.yml
template: |
  The Play Team is happy to announce the release of Play $NEXT_PATCH_VERSION.
  
  ## :green_book: What is new?
  
  The following are the relevant changes of this bugfix release:
  
  * TODO [#123](https://github.com/playframework/playframework/pull/123)
  * TODO [#123](https://github.com/playframework/playframework/issues/123)
  
  Following pull requests got merged for this release:
  
  $CHANGES
  
  For more details see the [full list of changes](https://github.com/playframework/playframework/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION/) and the [$NEXT_PATCH_VERSION milestone](https://github.com/playframework/playframework/issues?page=1&q=milestone%3A%22$NEXT_PATCH_VERSION%22).
  
  ## Migration
  
  TODO (please fill in or remove this heading)
